// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/iot.proto

package iot_ingestion_pipeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryPacket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Voltage          float64                `protobuf:"fixed64,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current          float64                `protobuf:"fixed64,3,opt,name=current,proto3" json:"current,omitempty"`
	TimestampNs      int64                  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	PayloadSignature []byte                 `protobuf:"bytes,5,opt,name=payload_signature,json=payloadSignature,proto3" json:"payload_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryPacket) Reset() {
	*x = TelemetryPacket{}
	mi := &file_proto_iot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPacket) ProtoMessage() {}

func (x *TelemetryPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPacket.ProtoReflect.Descriptor instead.
func (*TelemetryPacket) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPacket) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryPacket) GetVoltage() float64 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *TelemetryPacket) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *TelemetryPacket) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *TelemetryPacket) GetPayloadSignature() []byte {
	if x != nil {
		return x.PayloadSignature
	}
	return nil
}

type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_proto_iot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{1}
}

func (x *Acknowledgement) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Acknowledgement) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Acknowledgement) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_proto_iot_proto protoreflect.FileDescriptor

const file_proto_iot_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/iot.proto\x12\x03iot\"\xb2\x01\n" +
	"\x0fTelemetryPacket\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\avoltage\x18\x02 \x01(\x01R\avoltage\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\x01R\acurrent\x12!\n" +
	"\ftimestamp_ns\x18\x04 \x01(\x03R\vtimestampNs\x12+\n" +
	"\x11payload_signature\x18\x05 \x01(\fR\x10payloadSignature\"g\n" +
	"\x0fAcknowledgement\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg2Q\n" +
	"\fIoTIngestion\x12A\n" +
	"\x0fStreamTelemetry\x12\x14.iot.TelemetryPacket\x1a\x14.iot.Acknowledgement(\x010\x01B-Z+github.com/val-async/iot-ingestion-pipelineb\x06proto3"

var (
	file_proto_iot_proto_rawDescOnce sync.Once
	file_proto_iot_proto_rawDescData []byte
)

func file_proto_iot_proto_rawDescGZIP() []byte {
	file_proto_iot_proto_rawDescOnce.Do(func() {
		file_proto_iot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iot_proto_rawDesc), len(file_proto_iot_proto_rawDesc)))
	})
	return file_proto_iot_proto_rawDescData
}

var file_proto_iot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_iot_proto_goTypes = []any{
	(*TelemetryPacket)(nil), // 0: iot.TelemetryPacket
	(*Acknowledgement)(nil), // 1: iot.Acknowledgement
}
var file_proto_iot_proto_depIdxs = []int32{
	0, // 0: iot.IoTIngestion.StreamTelemetry:input_type -> iot.TelemetryPacket
	1, // 1: iot.IoTIngestion.StreamTelemetry:output_type -> iot.Acknowledgement
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_iot_proto_init() }
func file_proto_iot_proto_init() {
	if File_proto_iot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iot_proto_rawDesc), len(file_proto_iot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iot_proto_goTypes,
		DependencyIndexes: file_proto_iot_proto_depIdxs,
		MessageInfos:      file_proto_iot_proto_msgTypes,
	}.Build()
	File_proto_iot_proto = out.File
	file_proto_iot_proto_goTypes = nil
	file_proto_iot_proto_depIdxs = nil
}
