// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/iot.proto

package iot_ingestion_pipeline

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IoTIngestion_StreamTelemetry_FullMethodName = "/iot.IoTIngestion/StreamTelemetry"
)

// IoTIngestionClient is the client API for IoTIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IoTIngestionClient interface {
	// Bidirectional streaming for high-throughput ingestion
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryPacket, Acknowledgement], error)
}

type ioTIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewIoTIngestionClient(cc grpc.ClientConnInterface) IoTIngestionClient {
	return &ioTIngestionClient{cc}
}

func (c *ioTIngestionClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TelemetryPacket, Acknowledgement], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IoTIngestion_ServiceDesc.Streams[0], IoTIngestion_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryPacket, Acknowledgement]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IoTIngestion_StreamTelemetryClient = grpc.BidiStreamingClient[TelemetryPacket, Acknowledgement]

// IoTIngestionServer is the server API for IoTIngestion service.
// All implementations must embed UnimplementedIoTIngestionServer
// for forward compatibility.
type IoTIngestionServer interface {
	// Bidirectional streaming for high-throughput ingestion
	StreamTelemetry(grpc.BidiStreamingServer[TelemetryPacket, Acknowledgement]) error
	mustEmbedUnimplementedIoTIngestionServer()
}

// UnimplementedIoTIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIoTIngestionServer struct{}

func (UnimplementedIoTIngestionServer) StreamTelemetry(grpc.BidiStreamingServer[TelemetryPacket, Acknowledgement]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedIoTIngestionServer) mustEmbedUnimplementedIoTIngestionServer() {}
func (UnimplementedIoTIngestionServer) testEmbeddedByValue()                      {}

// UnsafeIoTIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IoTIngestionServer will
// result in compilation errors.
type UnsafeIoTIngestionServer interface {
	mustEmbedUnimplementedIoTIngestionServer()
}

func RegisterIoTIngestionServer(s grpc.ServiceRegistrar, srv IoTIngestionServer) {
	// If the following call panics, it indicates UnimplementedIoTIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IoTIngestion_ServiceDesc, srv)
}

func _IoTIngestion_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IoTIngestionServer).StreamTelemetry(&grpc.GenericServerStream[TelemetryPacket, Acknowledgement]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IoTIngestion_StreamTelemetryServer = grpc.BidiStreamingServer[TelemetryPacket, Acknowledgement]

// IoTIngestion_ServiceDesc is the grpc.ServiceDesc for IoTIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IoTIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot.IoTIngestion",
	HandlerType: (*IoTIngestionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _IoTIngestion_StreamTelemetry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/iot.proto",
}
